<a href="https://colab.research.google.com/github/satykrishna/python-frameworks/blob/main/Text_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from IPython.display import HTML, display

def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

In [25]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk) (3.1.2)

In [26]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('tagsets')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

True

In [27]:
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


text = 'India is a great country.'

tokens = word_tokenize(text)

stop_words = set(stopwords.words('english'))

filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

print(stop_words , '\n\n')

filtered_text = ' '.join(filtered_tokens)

print(filtered_text)

{"hasn't", 'she', 'after', 'through', 'other', "i've", 'themselves', "mightn't", "you're", 'in', 'the', 'for', "haven't", "i'll", 'is', 'this', 'such', 'm', 'ain', "you'll", 'all', 'same', 'what', 'it', 'wouldn', "you've", 'yourselves', "we're", 'him', "it'll", 'how', "we'd", 'again', 'by', 'with', "wouldn't", 'which', "mustn't", 'just', 'into', 'didn', 'own', 'shan', 'his', 'that', 'not', 'only', "she'd", "they'd", 'about', 'as', 'won', 'needn', 'but', 'few', 'we', 'aren', 'if', 'i', 'at', 'do', 'over', 'has', 'hadn', "he's", 'doing', 'having', "shan't", 'weren', "he'd", 'from', 'on', "should've", "couldn't", 'so', 'no', 't', 'down', 'been', "she'll", "isn't", 'were', 'be', "he'll", "won't", 'will', 'most', 'am', 'their', 'those', 'too', 'your', 'hers', 'there', 'who', "we've", 'you', 'y', 'o', 'during', 'can', 'and', 'does', 'ourselves', "wasn't", 'did', 'any', 'isn', 'being', 'once', "you'd", 'ma', "they've", 'wasn', "aren't", 'now', 're', 'then', 'herself', 'because', 'them', 'her', 'whom', 'of', 'these', 'they', 'a', 'me', 'mustn', 'some', 'had', "they'll", 'very', 'll', 'against', 'nor', 'off', "didn't", 's', 'above', "shouldn't", 'shouldn', 'than', 'theirs', 'mightn', 'have', "hadn't", 'both', 'each', 'haven', "it'd", 'are', "needn't", 'don', 'until', 've', 'my', 'itself', 'its', 'doesn', "she's", 'where', 'under', 'up', "that'll", 'yours', "doesn't", 'couldn', "i'd", 'before', 'why', 'or', 'while', "weren't", 'myself', 'more', 'between', "i'm", 'when', "we'll", 'further', 'himself', 'should', 'to', 'out', 'an', "it's", 'ours', "don't", "they're", 'here', 'd', 'below', 'was', 'yourself', 'he', 'our', 'hasn'}


India great country .

In [28]:
#Stemming --> Develop, Developed, Developing, Development ---> Develop
#Lemmatization --> Drive, Drives, Drove, Driven ---> Drive

In [29]:
#Stemming removes the last part of the word. --> present, past, future tense

In [30]:
import nltk
from nltk import pos_tag

sentence = 'The cat is sleeping on the mat'

tokens = word_tokenize(sentence)

print(tokens)

parts_of_speech_tags = pos_tag(tokens)

print(parts_of_speech_tags)

['The', 'cat', 'is', 'sleeping', 'on', 'the', 'mat']
[('The', 'DT'), ('cat', 'NN'), ('is', 'VBZ'), ('sleeping', 'VBG'), ('on', 'IN'), ('the', 'DT'), ('mat', 'NN')]

In [31]:
csv_url = 'https://raw.githubusercontent.com/elastic/examples/refs/heads/master/Machine%20Learning/Business%20Metrics%20Recipes/twitter_trends/data/tweets.csv$0'

In [32]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
!pip -q install --upgrade kagglehub

In [34]:
import kagglehub
from google.colab import userdata

assert userdata.get('KAGGLE_API_TOKEN'), 'KAGGLE_API_TOKEN is not set, it should be present'

In [35]:
dataset_path = kagglehub.dataset_download(
    "tango911/airline-sentiment-tweets",
)

print('downloaded to :', dataset_path)

Using Colab cache for faster access to the 'airline-sentiment-tweets' dataset.
Mounting files to /kaggle/input/airline-sentiment-tweets...

KeyboardInterrupt:

In [36]:
from pathlib import Path
import pandas as pd

csv_files = list(Path("/kaggle/input/airline-sentiment-tweets").rglob("*.csv"))

if not csv_files:
    raise FileNotFoundError("No CSV file found.")

df = pd.read_csv(csv_files[0])

print("File:", csv_files[0].name)
print("Shape:", df.shape)

File: train.csv
Shape: (3339, 12)

In [37]:
print(np.random.choice(df['text'], 5))

['@united well this one missed the mark.  She was in a snit from the minute I stepped up to the counter'
 '@VirginAmerica @ladygaga @carrieunderwood After last night #tribute #SoundOfMusic #Oscars2015 @ladygaga! I think @carrieunderwood agree'
 '@united Followback so I can DM plz'
 '@VirginAmerica I emailed your customer service team. Let me know if you need the tracking number.'
 '@united  found a group of people who actually hates people more than ISIS, thats right United Airlines.']

In [38]:
k = (df.loc[:5, 'text'].str.split(' '))
print(type(k))

<class 'pandas.core.series.Series'>

In [39]:
df.loc[:5, 'text'].str.lower().str.split(' ')

0             [@virginamerica, what, @dhepburn, said.]
1    [@virginamerica, plus, you've, added, commerci...
2    [@virginamerica, i, didn't, today..., must, me...
3    [@virginamerica, it's, really, aggressive, to,...
4    [@virginamerica, and, it's, a, really, big, ba...
5    [@virginamerica, seriously, would, pay, $30, a...
Name: text, dtype: object

In [40]:
df.loc[:5, 'text'].str.replace('@', '').str.lower().str.split(' ')

0               [virginamerica, what, dhepburn, said.]
1    [virginamerica, plus, you've, added, commercia...
2    [virginamerica, i, didn't, today..., must, mea...
3    [virginamerica, it's, really, aggressive, to, ...
4    [virginamerica, and, it's, a, really, big, bad...
5    [virginamerica, seriously, would, pay, $30, a,...
Name: text, dtype: object

In [41]:
#NLTK provide a function word_tokenize

for each in df.loc[:5, 'text']:
  print(nltk.word_tokenize(each))

['@', 'VirginAmerica', 'What', '@', 'dhepburn', 'said', '.']
['@', 'VirginAmerica', 'plus', 'you', "'ve", 'added', 'commercials', 'to', 'the', 'experience', '...', 'tacky', '.']
['@', 'VirginAmerica', 'I', 'did', "n't", 'today', '...', 'Must', 'mean', 'I', 'need', 'to', 'take', 'another', 'trip', '!']
['@', 'VirginAmerica', 'it', "'s", 'really', 'aggressive', 'to', 'blast', 'obnoxious', '``', 'entertainment', "''", 'in', 'your', 'guests', "'", 'faces', '&', 'amp', ';', 'they', 'have', 'little', 'recourse']
['@', 'VirginAmerica', 'and', 'it', "'s", 'a', 'really', 'big', 'bad', 'thing', 'about', 'it']
['@', 'VirginAmerica', 'seriously', 'would', 'pay', '$', '30', 'a', 'flight', 'for', 'seats', 'that', 'did', "n't", 'have', 'this', 'playing', '.', 'it', "'s", 'really', 'the', 'only', 'bad', 'thing', 'about', 'flying', 'VA']

In [42]:
from nltk.corpus import stopwords

sw_list = set(stopwords.words('english'))
sw_list.update(['@', "'", '.', '"', '/', '|', "'ve", "''", '...'])

tokenized_data = []

for each in df.loc[:2, 'text']:
  line = [word for word in nltk.word_tokenize(each) if word.lower() not in sw_list]
  tokenized_data.append(line)

print(tokenized_data)

[['VirginAmerica', 'dhepburn', 'said'], ['VirginAmerica', 'plus', 'added', 'commercials', 'experience', 'tacky'], ['VirginAmerica', "n't", 'today', 'Must', 'mean', 'need', 'take', 'another', 'trip', '!']]

In [43]:
df.loc[5, 'text'].lower().split('.')

["@virginamerica seriously would pay $30 a flight for seats that didn't have this playing",
 "\r\nit's really the only bad thing about flying va"]

In [44]:
nltk.sent_tokenize(df.loc[0, 'text'])

['@VirginAmerica What @dhepburn said.']

In [45]:
from nltk.stem import PorterStemmer

p_stemmer = PorterStemmer()

print(p_stemmer.stem('running'))
print(p_stemmer.stem('runs'))
print(p_stemmer.stem('ran'))

run
run
ran

In [46]:
from nltk.stem import SnowballStemmer

s_stemmer = SnowballStemmer('english')

print(s_stemmer.stem('running'))
print(s_stemmer.stem('runs'))
print(s_stemmer.stem('ran'))

run
run
ran

In [47]:
strings = df.loc[:5, 'text'].str.lower()

In [49]:
print(strings)

0                  @virginamerica what @dhepburn said.
1    @virginamerica plus you've added commercials t...
2    @virginamerica i didn't today... must mean i n...
3    @virginamerica it's really aggressive to blast...
4    @virginamerica and it's a really big bad thing...
5    @virginamerica seriously would pay $30 a fligh...
Name: text, dtype: object

In [48]:
from nltk import word_tokenize

words_in_each_string = []

for each_string in strings:
  words_in_each_string.append(word_tokenize(each_string))


words_in_each_string

[['@', 'virginamerica', 'what', '@', 'dhepburn', 'said', '.'],
 ['@',
  'virginamerica',
  'plus',
  'you',
  "'ve",
  'added',
  'commercials',
  'to',
  'the',
  'experience',
  '...',
  'tacky',
  '.'],
 ['@',
  'virginamerica',
  'i',
  'did',
  "n't",
  'today',
  '...',
  'must',
  'mean',
  'i',
  'need',
  'to',
  'take',
  'another',
  'trip',
  '!'],
 ['@',
  'virginamerica',
  'it',
  "'s",
  'really',
  'aggressive',
  'to',
  'blast',
  'obnoxious',
  '``',
  'entertainment',
  "''",
  'in',
  'your',
  'guests',
  "'",
  'faces',
  '&',
  'amp',
  ';',
  'they',
  'have',
  'little',
  'recourse'],
 ['@',
  'virginamerica',
  'and',
  'it',
  "'s",
  'a',
  'really',
  'big',
  'bad',
  'thing',
  'about',
  'it'],
 ['@',
  'virginamerica',
  'seriously',
  'would',
  'pay',
  '$',
  '30',
  'a',
  'flight',
  'for',
  'seats',
  'that',
  'did',
  "n't",
  'have',
  'this',
  'playing',
  '.',
  'it',
  "'s",
  'really',
  'the',
  'only',
  'bad',
  'thing',
  'about',
  'flying',
  'va']]

In [50]:
original_words_list = []

In [52]:
original_words_list = []
p_stemmed_list = []
s_stemmed_list = []

for each_word_list in words_in_each_string:
  original_words_list.extend(each_word_list)
  p_stemmed_list.extend([p_stemmer.stem(word) for word in each_word_list])
  s_stemmed_list.extend([s_stemmer.stem(word) for word in each_word_list])

data = pd.DataFrame(original_words_list, columns=['original_word'])
data['p_stemmed'] = p_stemmed_list
data['s_stemmed'] = s_stemmed_list

data

    original_word      p_stemmed      s_stemmed
0               @              @              @
1   virginamerica  virginamerica  virginamerica
2            what           what           what
3               @              @              @
4        dhepburn       dhepburn       dhepburn
..            ...            ...            ...
95            bad            bad            bad
96          thing          thing          thing
97          about          about          about
98         flying            fli            fli
99             va             va             va

[100 rows x 3 columns]

In [53]:
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print(lemmatizer.lemmatize('running'))
print(lemmatizer.lemmatize('runs'))
print(lemmatizer.lemmatize('ran'))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

running
run
ran

In [58]:
lemmatizer.lemmatize('ran', pos='v')

'run'

In [69]:
text = df.loc[5, 'text']
print(text)

@VirginAmerica seriously would pay $30 a flight for seats that didn't have this playing.
it's really the only bad thing about flying VA

In [68]:
token_list = nltk.word_tokenize(text)
token_list

['@',
 'VirginAmerica',
 'seriously',
 'would',
 'pay',
 '$',
 '30',
 'a',
 'flight',
 'for',
 'seats',
 'that',
 'did',
 "n't",
 'have',
 'this',
 'playing',
 '.',
 'it',
 "'s",
 'really',
 'the',
 'only',
 'bad',
 'thing',
 'about',
 'flying',
 'VA']

In [70]:
tokens_after_sw = []

for word in token_list:
  if word.lower() not in sw_list:
    tokens_after_sw.append(word)

tokens_after_sw

['VirginAmerica',
 'seriously',
 'would',
 'pay',
 '$',
 '30',
 'flight',
 'seats',
 "n't",
 'playing',
 "'s",
 'really',
 'bad',
 'thing',
 'flying',
 'VA']

In [71]:
tagged_tokens = nltk.pos_tag(tokens_after_sw)
tagged_tokens

[('VirginAmerica', 'NNP'),
 ('seriously', 'RB'),
 ('would', 'MD'),
 ('pay', 'VB'),
 ('$', '$'),
 ('30', 'CD'),
 ('flight', 'NN'),
 ('seats', 'NNS'),
 ("n't", 'RB'),
 ('playing', 'VBG'),
 ("'s", 'POS'),
 ('really', 'RB'),
 ('bad', 'JJ'),
 ('thing', 'NN'),
 ('flying', 'VBG'),
 ('VA', 'NNP')]

In [73]:
import nltk
nltk.download('tagsets_json')
nltk.help.upenn_tagset()

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or conjunction, subordinating
    astride among uppon whether out inside pro despite on by throughout
    below within for towards near behind atop around if like until below
    next into if beside ...
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
JJR: adjective, comparative
    bleaker braver breezier briefer brighter brisker broader bumper busier
    calmer cheaper choosier cleaner clearer closer colder commoner costlier
    cozier creamier crunchier cuter ...
JJS: adjective, superlative
    calmest cheapest choicest classiest cleanest clearest closest commonest
    corniest costliest crassest creepiest crudest cutest darkest deadliest
    dearest deepest densest dinkiest ...
LS: list item marker
    A A. B B. C C. D E F First G H I J K One SP-44001 SP-44002 SP-44005
    SP-44007 Second Third Three Two * a b c d first five four one six three
    two
MD: modal auxiliary
    can cannot could couldn't dare may might must need ought shall should
    shouldn't will would
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
NNP: noun, proper, singular
    Motown Venneboerger Czestochwa Ranzer Conchita Trumplane Christos
    Oceanside Escobar Kreisler Sawyer Cougar Yvette Ervin ODI Darryl CTCA
    Shannon A.K.C. Meltex Liverpool ...
NNPS: noun, proper, plural
    Americans Americas Amharas Amityvilles Amusements Anarcho-Syndicalists
    Andalusians Andes Andruses Angels Animals Anthony Antilles Antiques
    Apache Apaches Apocrypha ...
NNS: noun, common, plural
    undergraduates scotches bric-a-brac products bodyguards facets coasts
    divestitures storehouses designs clubs fragrances averages
    subjectivists apprehensions muses factory-jobs ...
PDT: pre-determiner
    all both half many quite such sure this
POS: genitive marker
    ' 's
PRP: pronoun, personal
    hers herself him himself hisself it itself me myself one oneself ours
    ourselves ownself self she thee theirs them themselves they thou thy us
PRP$: pronoun, possessive
    her his mine my our ours their thy your
RB: adverb
    occasionally unabatingly maddeningly adventurously professedly
    stirringly prominently technologically magisterially predominately
    swiftly fiscally pitilessly ...
RBR: adverb, comparative
    further gloomier grander graver greater grimmer harder harsher
    healthier heavier higher however larger later leaner lengthier less-
    perfectly lesser lonelier longer louder lower more ...
RBS: adverb, superlative
    best biggest bluntest earliest farthest first furthest hardest
    heartiest highest largest least less most nearest second tightest worst
RP: particle
    aboard about across along apart around aside at away back before behind
    by crop down ever fast for forth from go high i.e. in into just later
    low more off on open out over per pie raising start teeth that through
    under unto up up-pp upon whole with you
SYM: symbol
    % & ' '' ''. ) ). * + ,. < = > @ A[fj] U.S U.S.S.R * ** ***
TO: "to" as preposition or infinitive marker
    to
UH: interjection
    Goodbye Goody Gosh Wow Jeepers Jee-sus Hubba Hey Kee-reist Oops amen
    huh howdy uh dammit whammo shucks heck anyways whodunnit honey golly
    man baby diddle hush sonuvabitch ...
VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...
VBD: verb, past tense
    dipped pleaded swiped regummed soaked tidied convened halted registered
    cushioned exacted snubbed strode aimed adopted belied figgered
    speculated wore appreciated contemplated ...
VBG: verb, present participle or gerund
    telegraphing stirring focusing angering judging stalling lactating
    hankerin' alleging veering capping approaching traveling besieging
    encrypting interrupting erasing wincing ...
VBN: verb, past participle
    multihulled dilapidated aerosolized chaired languished panelized used
    experimented flourished imitated reunifed factored condensed sheared
    unsettled primed dubbed desired ...
VBP: verb, present tense, not 3rd person singular
    predominate wrap resort sue twist spill cure lengthen brush terminate
    appear tend stray glisten obtain comprise detest tease attract
    emphasize mold postpone sever return wag ...
VBZ: verb, present tense, 3rd person singular
    bases reconstructs marks mixes displeases seals carps weaves snatches
    slumps stretches authorizes smolders pictures emerges stockpiles
    seduces fizzes uses bolsters slaps speaks pleads ...
WDT: WH-determiner
    that what whatever which whichever
WP: WH-pronoun
    that what whatever whatsoever which who whom whosoever
WP$: WH-pronoun, possessive
    whose
WRB: Wh-adverb
    how however whence whenever where whereby whereever wherein whereof why
``: opening quotation mark
    ` ``

[nltk_data] Downloading package tagsets_json to /root/nltk_data...
[nltk_data]   Unzipping help/tagsets_json.zip.